name: Simple CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Print status message
        run: echo "Pipeline is running successfully!"

      - name: List files in repository
        run: ls -la
